apiVersion: v1
kind: Template
labels:
  template: bayesian-hpf-insights
metadata:
  name: bayesian-hpf-insights
  annotations:
    description: bayesian-hpf-insights
objects:
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    labels:
      service: bayesian-hpf-insights-${HPF_SCORING_REGION}
    name: bayesian-hpf-insights-${HPF_SCORING_REGION}
  spec:
    replicas: "${{REPLICAS}}"
    selector:
      service: bayesian-hpf-insights-${HPF_SCORING_REGION}
    template:
      metadata:
        labels:
          service: bayesian-hpf-insights-${HPF_SCORING_REGION}
      spec:
        containers:
        - command:
          - /bin/entrypoint.sh
          env:
            # For testing config is DEV
            #TODO: Load from deployment config
          - name: DEPLOYMENT_PREFIX
            value: "DEV"
          - name: SERVICE_PORT
            value: "6006"
          - name: SERVICE_TIMEOUT
            value: "900"
          - name: HPF_SCORING_REGION
            value: "${HPF_SCORING_REGION}"
          - name: AWS_S3_ENDPOINT_URL
            value: ""
          - name: AWS_S3_BUCKET_NAME
            value: "hpf-insights"
          - name: FLASK_LOGGING_LEVEL
            value: ${FLASK_LOGGING_LEVEL}
          - name: AWS_S3_ACCESS_KEY_ID
            valueFrom:
              secretKeyRef:
                key: s3-access-key-id
                name: aws
          - name: AWS_S3_SECRET_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                key: s3-secret-access-key
                name: aws
          name: bayesian-hpf-insights
          image: "${DOCKER_REGISTRY}/${DOCKER_IMAGE}:${IMAGE_TAG}"
          ports:
          - containerPort: 6006
          livenessProbe:
            httpGet:
              path: /
              port: 6006
            initialDelaySeconds: 30
            periodSeconds: 60
            timeoutSeconds: 30
          readinessProbe:
            httpGet:
              path: /
              port: 6006
            initialDelaySeconds: 30
            periodSeconds: 60
            timeoutSeconds: 30
          resources:
            requests:
              cpu: ${CPU_REQUEST}
              memory: ${MEMORY_REQUEST}
            limits:
              cpu: ${CPU_LIMIT}
              memory: ${MEMORY_LIMIT}
          #Add so that .npy can be downloaded from s3 and saved under /tmp. Gives write permission error otherwise.
          volumeMounts:
          - name: s3-data
            mountPath: /tmp
        volumes:
        - name: s3-data
          emptyDir: {}
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      service: bayesian-hpf-insights-${HPF_SCORING_REGION}
    name: bayesian-hpf-insights-${HPF_SCORING_REGION}
  spec:
    ports:
    - port: 6006
      targetPort: 0
    selector:
      service: bayesian-hpf-insights-${HPF_SCORING_REGION}

parameters:
- description: CPU request
  displayName: CPU request
  required: true
  name: CPU_REQUEST
  value: "500m"

- description: CPU limit
  displayName: CPU limit
  required: true
  name: CPU_LIMIT
  value: "1000m"

- description: Memory request
  displayName: Memory request
  required: true
  name: MEMORY_REQUEST
  value: "1024Mi"

- description: Memory limit
  displayName: Memory limit
  required: true
  name: MEMORY_LIMIT
  value: "2048Mi"

# For testing, image on Docker
# TODO: Change to registry.devshift
- description: Docker registry where the image is
  displayName: Docker registry
  required: true
  name: DOCKER_REGISTRY
  value: "docker.io"

# For testing, image on Docker
# TODO: image name to follow f8a-image conventions.
- description: Docker image to use
  displayName: Docker image
  required: true
  name: DOCKER_IMAGE
  value: "sara02/hpf-insights"

- description: Image tag
  displayName: Image tag
  required: true
  name: IMAGE_TAG
  value: "latest"

- description: HPF Scoring Region - pypi or maven
  displayName: HPF Scoring Region
  required: true
  name: HPF_SCORING_REGION
  value: "maven"

- description: "Flask logging level (see: https://docs.python.org/3/library/logging.html#levels)"
  displayName: Flask logging level
  required: false
  name: FLASK_LOGGING_LEVEL
  value: "INFO"

- description: Number of deployment replicas
  displayName: Number of deployment replicas
  required: true
  name: REPLICAS
  value: "1"